/**
 * English strings (SPEC §14 seed plus item and collection names from §11.2 and §4).
 * Keys are namespaced; values are whole sentences with {placeholders}.
 */
export const en = {
  'app.title': 'Tick-Tock',
  'room.space': 'Space Playroom',
  'room.sweet': 'Sweet Playroom',
  'companion.space': 'Pip',
  'companion.sweet': 'Mimi',

  's0.choose': 'Choose a room',
  's0.lang.title': 'Which language?',
  's0.lang.en': 'English',
  's0.lang.tr': 'Türkçe',
  's0.lang.nl': 'Nederlands',

  's1.rooms': 'Rooms',
  's1.decorate': 'Decorate',
  's1.dressup': 'Dress up',
  's1.mission': 'Choose a mission',
  's1.collected': '{n} / {total} collected',
  's1.nextPrizes': 'What will you earn next?',

  'panel.decorations': 'Decorations',
  'panel.clothes': 'Clothes',
  'panel.shoes': 'Shoes',
  'panel.hair': 'Hair',
  'panel.extras': 'Extras',
  'panel.nothing': 'Nothing',
  'panel.inRoom': 'In room',
  'panel.new': 'New',
  'panel.close': 'Close',

  'slot.BED': 'Bed',
  'slot.RUG': 'Rug',
  'slot.LAMP': 'Lamp',
  'slot.WALL': 'Wall',
  'slot.SHELF': 'Shelf',
  'slot.HANGING': 'Ceiling',
  'slot.NOOK': 'Cosy corner',

  'mission.a.space': 'Rocket launch',
  'mission.a.space.desc': 'Read and set clocks to get the rocket ready.',
  'mission.b.space': 'Space delivery',
  'mission.b.space.desc': 'A parcel is flying between planets. How long does it take?',
  'mission.a.sweet': 'Tea-party time',
  'mission.a.sweet.desc': 'Read and set clocks to get the tea party ready.',
  'mission.b.sweet': 'Toy delivery',
  'mission.b.sweet.desc': 'A parcel is on its way to the playroom. How long does it take?',

  'level.r1': 'Whole hours',
  'level.r2': 'Half hours',
  'level.r3': 'Quarter hours',
  'level.r4': 'Five minutes',
  'level.e1': 'Whole hours',
  'level.e2': 'Quarters',
  'level.e3': 'Long journeys',

  's2.prizes': 'Prizes waiting',
  's2.allCollected': 'All prizes collected! Missions now earn stars.',
  's2.start': 'Start',
  's2.back': 'Back to room',
  's2.locked': 'Levels are locked by a grown-up',

  'a.story.space': 'Get the rocket ready!',
  'a.story.sweet': 'Get the tea party ready!',
  'a.read.q': 'What time is it?',
  'a.match.q': 'Which clock shows this time: {time}?',
  'a.set.q': 'Set the clock to {time}.',
  'a.set.check': 'Check',
  'a.set.wholeHours': 'At whole hours the long hand stays on 12.',
  'a.set.minusHour': '− 1 hour',
  'a.set.plusHour': '+ 1 hour',
  'a.set.minusStep': '− {m} min',
  'a.set.plusStep': '+ {m} min',
  'a.match.label': 'Clock {letter}',
  'a.set.clockLabel': 'Clock you can set',
  'a.shift.later.space': 'The rocket launches in {delta}. What time will it be?',
  'a.shift.ago.space': 'The countdown started {delta} ago. What time was it?',
  'a.shift.later.sweet': 'The guests arrive in {delta}. What time will it be?',
  'a.shift.ago.sweet': 'The cake went into the oven {delta} ago. What time was it?',
  'a.shift.clockLabel': 'Clock showing the time now',
  'clock.analog': 'Analog clock',
  'a.steps.space.1': 'Fuel',
  'a.steps.space.2': 'Hatch',
  'a.steps.space.3': 'Lights',
  'a.steps.space.4': 'Countdown',
  'a.steps.sweet.1': 'Cups',
  'a.steps.sweet.2': 'Cake',
  'a.steps.sweet.3': 'Teapot',
  'a.steps.sweet.4': 'Guests',

  'b.story.space': 'Your parcel is on its way!',
  'b.story.sweet': 'A parcel is coming to the playroom!',
  'b.q.space': 'How long is the journey?',
  'b.q.sweet': 'How long does the delivery take?',
  'b.leaves': 'Leaves',
  'b.arrives': 'Arrives',
  'b.showJumps': 'Show the jumps',
  'b.hideJumps': 'Hide the jumps',
  'b.sched.q': 'How long does {activity} take?',
  'b.sched.label': 'Day plan',
  'b.sched.segment': '{activity} from {start} to {end}',
  'sched.space.1': 'waking up',
  'sched.space.2': 'breakfast',
  'sched.space.3': 'refuelling',
  'sched.space.4': 'training',
  'sched.space.5': 'the launch check',
  'sched.space.6': 'stargazing',
  'sched.sweet.1': 'waking up',
  'sched.sweet.2': 'baking',
  'sched.sweet.3': 'decorating',
  'sched.sweet.4': 'the tea party',
  'sched.sweet.5': 'games',
  'sched.sweet.6': 'story time',

  // Times in words (SPEC §7.7): {h} is the hour the phrase names (see core/words.ts).
  'words.m0': "{h} o'clock",
  'words.m5': 'five past {h}',
  'words.m10': 'ten past {h}',
  'words.m15': 'quarter past {h}',
  'words.m20': 'twenty past {h}',
  'words.m25': 'twenty-five past {h}',
  'words.m30': 'half past {h}',
  'words.m35': 'twenty-five to {h}',
  'words.m40': 'twenty to {h}',
  'words.m45': 'quarter to {h}',
  'words.m50': 'ten to {h}',
  'words.m55': 'five to {h}',

  'dur.hm': '{h} hours {m} minutes',
  'dur.h1m': '1 hour {m} minutes',
  'dur.h': '{h} hours',
  'dur.h1': '1 hour',
  'dur.m': '{m} minutes',
  'dur.short.h': '+{h} h',
  'dur.short.m': '+{m} min',

  'period.morning': 'morning',
  'period.afternoon': 'afternoon',
  'period.evening': 'evening',
  'period.night': 'night',

  'q.progress': 'Question {k} of 4',
  'q.hint': 'Hint',
  'q.next': 'Next',
  'q.leave': 'Leave',

  'hint.minutes': '{m} minutes',
  'hint.hourPast': 'The short hand is just past {h}.',
  'hint.hourExact': 'The short hand points exactly at {h}.',
  'hint.matchShort': 'short hand → {h}',
  'hint.matchLong': 'long hand → {m}',
  'hint.wordsDigital': '{words} = {time}',
  'hint.shift': 'The faint hands show the new time.',

  'fb.correct.1': 'Yes!',
  'fb.correct.2': "That's it!",
  'fb.correct.3': 'Great!',
  'fb.wrong.1': 'Not yet, try again.',
  'fb.wrong.2': 'Almost. Look again.',
  'fb.wrong.3': 'Hmm, one more try.',
  'fb.tryAgain': 'Try again',
  'fb.setWrong': 'Not yet. Look at the short hand.',

  'leave.title': 'Leave the mission?',
  'leave.body': 'The puzzles so far will be lost. Your room and prizes are safe.',
  'leave.confirm': 'Leave',
  'leave.cancel': 'Keep going',

  's5.title': 'Mission complete!',
  's5.sub': '4 clock puzzles solved',
  's5.choose': 'Choose your prize',
  's5.place': 'Put it in my room',
  's5.wear': 'Wear it',
  's5.keep': 'Keep playing',
  's5.star': 'You earned a star!',
  's5.starFull': 'Your star chart is full!',
  's5.backRoom': 'Back to my room',
  's5.preview': 'Room preview',
  's5.starCount': '{n} of {total} stars',

  'prog.title': 'Ready for a bigger challenge?',
  'prog.try': 'Try {level}',
  'prog.notYet': 'Not yet',

  's6.title': 'Parent corner',
  's6.hold': 'Press and hold',
  's6.language': 'Language',
  's6.levels': 'Levels',
  's6.lock': 'Lock levels (child cannot change them)',
  's6.hour24': '24-hour digital clocks in reading puzzles',
  's6.timeWords': 'Times in words (quarter past 3)',
  's6.sound': 'Sound',
  's6.motion': 'Motion',
  's6.motion.system': 'Follow system',
  's6.motion.reduced': 'Reduced',
  's6.motion.full': 'Full',
  's6.export': 'Export save file',
  's6.import': 'Import save file',
  's6.reset': 'Reset everything (hold)',
  's6.recent': 'Recent missions',
  's6.privacy': 'Nothing is collected or sent anywhere.',
  's6.done': 'Done',
  's6.damagedSave': 'A damaged save was replaced on {date}.',
  's6.newerSave': 'A save from a newer version was set aside on {date}.',

  // S6 sections and controls (adult-facing text; SPEC §14 allows additions).
  's6.reading': 'Reading level',
  's6.elapsed': 'Elapsed-time level',
  'level.r1.desc': 'Whole hours only (3:00).',
  'level.r2.desc': 'Whole and half hours (3:30).',
  'level.r3.desc': 'Quarter hours (3:15, 3:45).',
  'level.r4.desc': 'Every five minutes (3:05, 3:50).',
  'level.e1.desc': 'Gaps of 1 to 5 whole hours.',
  'level.e2.desc': 'Quarter-hour gaps up to 2 hours.',
  'level.e3.desc': 'Gaps from 2 h 15 min to 6 hours.',
  's6.clock': 'Clock options',
  's6.save': 'Save file',
  's6.about': 'About',
  's6.version': 'Version {version}',
  's6.credits': 'Made with Preact and Vite. Font: Nunito (open font licence).',
  's6.exportDone': 'Save file downloaded.',
  's6.importTitle': 'Import this save?',
  's6.importSummary':
    'This file has {space} Space and {sweet} Sweet prizes, {stars} stars, last saved {date}. The current save is kept as a backup.',
  's6.importConfirm': 'Replace',
  's6.cancel': 'Cancel',
  's6.imported': 'Save imported.',
  's6.importInvalid': 'That file is not a Tick-Tock save.',
  's6.importNewer': 'That save comes from a newer version of the game.',
  's6.recentEmpty': 'No missions yet.',
  's6.col.when': 'When',
  's6.col.mission': 'Mission',
  's6.col.level': 'Level',
  's6.col.wrong': 'Wrong',
  's6.col.hints': 'Hints',
  's6.col.time': 'Time',
  's6.col.prize': 'Prize',
  's6.star': 'Star',
  's6.dismiss': 'Dismiss',
  'ui.on': 'On',
  'ui.off': 'Off',
  'ui.starChart': 'Star chart',

  'ui.soundOn': 'Sound on',
  'ui.soundOff': 'Sound off',
  'ui.parentCorner': 'Parent corner',
  'ui.language': 'Language',
  'ui.answers': 'Answers',
  'ui.heroine': 'Me',
  'ui.tiles': 'Items',
  'ui.tabs': 'Wardrobe',
  'ui.themeBadge.space': 'From the Space Playroom',
  'ui.themeBadge.sweet': 'From the Sweet Playroom',
  'ui.collectionDots': 'Collections',
  'ui.pickSlot': 'Now choose where it goes.',
  'ui.placed': '{item} is in the room.',
  'ui.worn': 'Wearing {item}.',

  'collection.space.moonSleepover': 'Moon Sleepover',
  'collection.space.rainbowExplorer': 'Rainbow Explorer',
  'collection.sweet.sweetSleepover': 'Sweet Sleepover',
  'collection.sweet.sunnyGarden': 'Sunny Garden',

  // Shared wardrobe starters (SPEC §4.4).
  'item.shared.hairBuns': 'Two buns',
  'item.shared.hairPonytail': 'High ponytail',
  'item.shared.hairLoose': 'Loose with clip',
  'item.shared.outfitPlanetTee': 'Planet tee and mint skirt',
  'item.shared.outfitFloralSweater': 'Floral sweater and pinafore',
  'item.shared.outfitStarHoodie': 'Star hoodie and trousers',
  'item.shared.shoesSneakers': 'Yellow socks and sneakers',
  'item.shared.shoesMaryJanes': 'Pink mary-janes',

  // Space starters (SPEC §4.1).
  'item.space.plainBed': 'Plain blue bed',
  'item.space.plainRug': 'Plain round rug',
  'item.space.plainLamp': 'Plain lamp',
  'item.space.rocketPoster': 'Rocket poster',
  'item.space.astronautFigure': 'Astronaut figure',
  'item.space.paperStars': 'Paper star string',
  'item.space.purpleBeanbag': 'Purple beanbag',
  // Space earnables (SPEC §11.2).
  'item.space.moonBed': 'Moon bed',
  'item.space.starLamp': 'Star lamp',
  'item.space.astroBunny': 'Astronaut bunny',
  'item.space.cloudPyjamas': 'Cloud pyjamas',
  'item.space.bunnySlippers': 'Bunny slippers',
  'item.space.starClip': 'Star hair clip',
  'item.space.rainbowRug': 'Rainbow rug',
  'item.space.planetMobile': 'Planet mobile',
  'item.space.galaxyPoster': 'Galaxy poster',
  'item.space.spacesuit': 'Colourful spacesuit',
  'item.space.spaceBoots': 'Space boots',
  'item.space.rocketBackpack': 'Rocket backpack',

  // Sweet starters (SPEC §4.1).
  'item.sweet.plainBed': 'Plain pink bed',
  'item.sweet.plainRug': 'Plain dotted rug',
  'item.sweet.plainLamp': 'Plain lamp',
  'item.sweet.tulipPicture': 'Tulip picture',
  'item.sweet.bunnyPlush': 'Bunny plush',
  'item.sweet.bunting': 'Bunting',
  'item.sweet.yellowCushion': 'Yellow sofa cushion',
  // Sweet earnables (SPEC §11.2).
  'item.sweet.flowerCushion': 'Flower cushion',
  'item.sweet.pastelRug': 'Pastel rug',
  'item.sweet.heartLamp': 'Heart lamp',
  'item.sweet.floralPyjamas': 'Floral pyjamas',
  'item.sweet.catSlippers': 'Cat slippers',
  'item.sweet.flowerClip': 'Flower hair clip',
  'item.sweet.daisyBed': 'Daisy bed',
  'item.sweet.butterflyMobile': 'Butterfly mobile',
  'item.sweet.sunPoster': 'Sunshine poster',
  'item.sweet.strawberryDress': 'Strawberry dress',
  'item.sweet.rainbowSandals': 'Rainbow sandals',
  'item.sweet.bowHeadband': 'Bow headband',
} as const satisfies Record<string, string>;

export type StringKey = keyof typeof en;
