import type { StringKey } from './en.ts';

/**
 * Dutch strings (SPEC §14 seed). Informal "je"; hands are "grote wijzer" and "kleine wijzer".
 * Dutch strings are usually the longest, so layouts are checked in Dutch first.
 * Starter item names are new and marked for native review.
 */
export const nl: Record<StringKey, string> = {
  'app.title': 'My Cosmic Room',
  'room.space': 'Ruimtespeelkamer',
  'room.sweet': 'Zoete speelkamer',
  'companion.space': 'Pip',
  'companion.sweet': 'Mimi',

  's0.choose': 'Kies een kamer',
  's0.lang.title': 'Welke taal?',
  's0.lang.en': 'English',
  's0.lang.tr': 'Türkçe',
  's0.lang.nl': 'Nederlands',

  's1.rooms': 'Kamers',
  's1.decorate': 'Inrichten',
  's1.dressup': 'Verkleden',
  's1.mission': 'Kies een missie',
  's1.collected': '{n} / {total} verzameld',
  's1.nextPrizes': 'Wat verdien je hierna?',

  'panel.decorations': 'Versieringen',
  'panel.clothes': 'Kleren',
  'panel.shoes': 'Schoenen',
  'panel.hair': 'Haar',
  'panel.extras': "Extra's",
  'panel.nothing': 'Niets',
  'panel.inRoom': 'In de kamer',
  'panel.new': 'Nieuw',
  'panel.close': 'Sluiten',

  'slot.BED': 'Bed',
  'slot.RUG': 'Kleed',
  'slot.LAMP': 'Lamp',
  'slot.WALL': 'Muur',
  'slot.SHELF': 'Plank',
  'slot.HANGING': 'Plafond',
  'slot.NOOK': 'Knus hoekje',

  'mission.a.space': 'Raketlancering',
  'mission.a.space.desc': 'Lees en zet klokken om de raket klaar te maken.',
  'mission.b.space': 'Ruimtebezorging',
  'mission.b.space.desc': 'Een pakje vliegt tussen planeten. Hoe lang duurt dat?',
  'mission.a.sweet': 'Theekransje',
  'mission.a.sweet.desc': 'Lees en zet klokken om het theekransje klaar te maken.',
  'mission.b.sweet': 'Speelgoedbezorging',
  'mission.b.sweet.desc': 'Een pakje is onderweg naar de speelkamer. Hoe lang duurt dat?',

  'level.r1': 'Hele uren',
  'level.r2': 'Halve uren',
  'level.r3': 'Kwartieren',
  'level.r4': 'Vijf minuten',
  'level.e1': 'Hele uren',
  'level.e2': 'Kwartieren',
  'level.e3': 'Lange reizen',

  's2.prizes': 'Prijzen voor jou',
  's2.allCollected': 'Alle prijzen verzameld! Missies leveren nu sterren op.',
  's2.start': 'Start',
  's2.back': 'Terug naar de kamer',
  's2.locked': 'De niveaus zijn vergrendeld door een volwassene',

  'a.story.space': 'Maak de raket klaar!',
  'a.story.sweet': 'Maak het theekransje klaar!',
  'a.read.q': 'Hoe laat is het?',
  'a.match.q': 'Welke klok laat deze tijd zien: {time}?',
  'a.set.q': 'Zet de klok op {time}.',
  'a.set.check': 'Controleer',
  'a.set.wholeHours': 'Bij hele uren blijft de grote wijzer op de 12.',
  'a.set.minusHour': '− 1 uur',
  'a.set.plusHour': '+ 1 uur',
  'a.set.minusStep': '− {m} min',
  'a.set.plusStep': '+ {m} min',
  'a.match.label': 'Klok {letter}',
  'a.set.clockLabel': 'Klok die je kunt instellen',
  'clock.analog': 'Analoge klok',
  'a.steps.space.1': 'Brandstof',
  'a.steps.space.2': 'Luik',
  'a.steps.space.3': 'Lichten',
  'a.steps.space.4': 'Aftellen',
  'a.steps.sweet.1': 'Kopjes',
  'a.steps.sweet.2': 'Taart',
  'a.steps.sweet.3': 'Theepot',
  'a.steps.sweet.4': 'Gasten',

  'b.story.space': 'Je pakje is onderweg!',
  'b.story.sweet': 'Er komt een pakje naar de speelkamer!',
  'b.q.space': 'Hoe lang duurt de reis?',
  'b.q.sweet': 'Hoe lang duurt de bezorging?',
  'b.leaves': 'Vertrek',
  'b.arrives': 'Aankomst',
  'b.showJumps': 'Laat de sprongen zien',
  'b.hideJumps': 'Verberg de sprongen',

  'dur.hm': '{h} uur {m} minuten',
  'dur.h1m': '1 uur {m} minuten',
  'dur.h': '{h} uur',
  'dur.h1': '1 uur',
  'dur.m': '{m} minuten',
  'dur.short.h': '+{h} u',
  'dur.short.m': '+{m} min',

  'period.morning': 'ochtend',
  'period.afternoon': 'middag',
  'period.evening': 'avond',
  'period.night': 'nacht',

  'q.progress': 'Vraag {k} van 4',
  'q.hint': 'Hint',
  'q.next': 'Volgende',
  'q.leave': 'Stoppen',

  'hint.minutes': '{m} minuten',
  'hint.hourPast': 'De kleine wijzer is net voorbij de {h}.',
  'hint.hourExact': 'De kleine wijzer wijst precies naar de {h}.',
  'hint.matchShort': 'kleine wijzer → {h}',
  'hint.matchLong': 'grote wijzer → {m}',

  'fb.correct.1': 'Ja!',
  'fb.correct.2': "Dat is 'm!",
  'fb.correct.3': 'Super!',
  'fb.wrong.1': 'Nog niet, probeer het nog eens.',
  'fb.wrong.2': 'Bijna. Kijk nog eens.',
  'fb.wrong.3': 'Hmm, nog één keer.',
  'fb.tryAgain': 'Probeer opnieuw',
  'fb.setWrong': 'Nog niet. Kijk naar de kleine wijzer.',

  'leave.title': 'De missie verlaten?',
  'leave.body': 'De puzzels tot nu toe gaan verloren. Je kamer en prijzen zijn veilig.',
  'leave.confirm': 'Verlaten',
  'leave.cancel': 'Doorgaan',

  's5.title': 'Missie voltooid!',
  's5.sub': '4 klokpuzzels opgelost',
  's5.choose': 'Kies je prijs',
  's5.place': 'Zet het in mijn kamer',
  's5.wear': 'Doe het aan',
  's5.keep': 'Verder spelen',
  's5.star': 'Je hebt een ster verdiend!',
  's5.starFull': 'Je sterrenkaart is vol!',
  's5.backRoom': 'Terug naar mijn kamer',
  's5.preview': 'Voorbeeld van de kamer',
  's5.starCount': '{n} van {total} sterren',

  'prog.title': 'Klaar voor een grotere uitdaging?',
  'prog.try': 'Probeer {level}',
  'prog.notYet': 'Nog niet',

  's6.title': 'Ouderhoek',
  's6.hold': 'Houd ingedrukt',
  's6.language': 'Taal',
  's6.levels': 'Niveaus',
  's6.lock': 'Niveaus vergrendelen (kind kan ze niet wijzigen)',
  's6.hour24': 'Digitale 24-uursklokken in leespuzzels',
  's6.sound': 'Geluid',
  's6.motion': 'Beweging',
  's6.motion.system': 'Volg systeem',
  's6.motion.reduced': 'Verminderd',
  's6.motion.full': 'Volledig',
  's6.export': 'Opslagbestand exporteren',
  's6.import': 'Opslagbestand importeren',
  's6.reset': 'Alles wissen (ingedrukt houden)',
  's6.recent': 'Recente missies',
  's6.privacy': 'Er wordt niets verzameld of verstuurd.',
  's6.done': 'Klaar',
  's6.damagedSave': 'Een beschadigd opslagbestand is op {date} vervangen.',
  's6.newerSave': 'Een opslagbestand van een nieuwere versie is op {date} apart gezet.',

  'ui.soundOn': 'Geluid aan',
  'ui.soundOff': 'Geluid uit',
  'ui.parentCorner': 'Ouderhoek',
  'ui.language': 'Taal',
  'ui.answers': 'Antwoorden',

  'collection.space.moonSleepover': 'Maanlogeerpartij',
  'collection.space.rainbowExplorer': 'Regenboogontdekker',
  'collection.sweet.sweetSleepover': 'Zoete logeerpartij',
  'collection.sweet.sunnyGarden': 'Zonnige tuin',

  'item.shared.hairBuns': 'Twee knotjes',
  'item.shared.hairPonytail': 'Hoge paardenstaart',
  'item.shared.hairLoose': 'Los met speldje',
  'item.shared.outfitPlanetTee': 'Planetenshirt met mintrok',
  'item.shared.outfitFloralSweater': 'Bloementrui met overgooier',
  'item.shared.outfitStarHoodie': 'Sterrenhoodie met broek',
  'item.shared.shoesSneakers': 'Gele sokken met sneakers',
  'item.shared.shoesMaryJanes': 'Roze bandschoentjes',

  'item.space.plainBed': 'Gewoon blauw bed',
  'item.space.plainRug': 'Gewoon rond kleed',
  'item.space.plainLamp': 'Gewone lamp',
  'item.space.rocketPoster': 'Raketposter',
  'item.space.astronautFigure': 'Astronautenfiguur',
  'item.space.paperStars': 'Papieren sterrenslinger',
  'item.space.purpleBeanbag': 'Paarse zitzak',
  'item.space.moonBed': 'Maanbed',
  'item.space.starLamp': 'Sterrenlamp',
  'item.space.astroBunny': 'Astronautenkonijn',
  'item.space.cloudPyjamas': 'Wolkenpyjama',
  'item.space.bunnySlippers': 'Konijnensloffen',
  'item.space.starClip': 'Sterrenspeldje',
  'item.space.rainbowRug': 'Regenboogkleed',
  'item.space.planetMobile': 'Planetenmobiel',
  'item.space.galaxyPoster': 'Melkwegposter',
  'item.space.spacesuit': 'Kleurrijk ruimtepak',
  'item.space.spaceBoots': 'Ruimtelaarzen',
  'item.space.rocketBackpack': 'Raketrugzak',

  'item.sweet.plainBed': 'Gewoon roze bed',
  'item.sweet.plainRug': 'Gewoon stippenkleed',
  'item.sweet.plainLamp': 'Gewone lamp',
  'item.sweet.tulipPicture': 'Tulpenschilderij',
  'item.sweet.bunnyPlush': 'Knuffelkonijn',
  'item.sweet.bunting': 'Vlaggenlijn',
  'item.sweet.yellowCushion': 'Geel bankkussen',
  'item.sweet.flowerCushion': 'Bloemenkussen',
  'item.sweet.pastelRug': 'Pastelkleed',
  'item.sweet.heartLamp': 'Hartjeslamp',
  'item.sweet.floralPyjamas': 'Bloemetjespyjama',
  'item.sweet.catSlippers': 'Kattensloffen',
  'item.sweet.flowerClip': 'Bloemenspeldje',
  'item.sweet.daisyBed': 'Madeliefjesbed',
  'item.sweet.butterflyMobile': 'Vlindermobiel',
  'item.sweet.sunPoster': 'Zonnetjesposter',
  'item.sweet.strawberryDress': 'Aardbeienjurk',
  'item.sweet.rainbowSandals': 'Regenboogsandalen',
  'item.sweet.bowHeadband': 'Haarband met strik',
};
