import type { StringKey } from './en.ts';

/**
 * Turkish strings (SPEC §14 seed). Level names reuse the early concept labels
 * (Tam saat, Buçuk, Çeyrek). Starter item names are new and marked for native review.
 */
export const tr: Record<StringKey, string> = {
  'app.title': 'My Cosmic Room',
  'room.space': 'Uzay Oyun Odası',
  'room.sweet': 'Tatlı Oyun Odası',
  'companion.space': 'Pip',
  'companion.sweet': 'Mimi',

  's0.choose': 'Bir oda seç',
  's0.lang.title': 'Hangi dil?',
  's0.lang.en': 'English',
  's0.lang.tr': 'Türkçe',
  's0.lang.nl': 'Nederlands',

  's1.rooms': 'Odalar',
  's1.decorate': 'Süsle',
  's1.dressup': 'Giydir',
  's1.mission': 'Görev seç',
  's1.collected': '{n} / {total} toplandı',
  's1.nextPrizes': 'Sırada ne kazanacaksın?',

  'panel.decorations': 'Süsler',
  'panel.clothes': 'Kıyafetler',
  'panel.shoes': 'Ayakkabılar',
  'panel.hair': 'Saç',
  'panel.extras': 'Aksesuarlar',
  'panel.nothing': 'Hiçbiri',
  'panel.inRoom': 'Odada',
  'panel.new': 'Yeni',
  'panel.close': 'Kapat',

  'slot.BED': 'Yatak',
  'slot.RUG': 'Halı',
  'slot.LAMP': 'Lamba',
  'slot.WALL': 'Duvar',
  'slot.SHELF': 'Raf',
  'slot.HANGING': 'Tavan',
  'slot.NOOK': 'Rahat köşe',

  'mission.a.space': 'Roket Fırlatma',
  'mission.a.space.desc': 'Roketi hazırlamak için saatleri oku ve ayarla.',
  'mission.b.space': 'Uzay Teslimatı',
  'mission.b.space.desc': 'Bir paket gezegenler arasında uçuyor. Ne kadar sürer?',
  'mission.a.sweet': 'Çay Partisi Saati',
  'mission.a.sweet.desc': 'Çay partisini hazırlamak için saatleri oku ve ayarla.',
  'mission.b.sweet': 'Oyuncak Teslimatı',
  'mission.b.sweet.desc': 'Oyun odasına bir paket geliyor. Ne kadar sürer?',

  'level.r1': 'Tam saat',
  'level.r2': 'Buçuk',
  'level.r3': 'Çeyrek',
  'level.r4': 'Beş dakika',
  'level.e1': 'Tam saat',
  'level.e2': 'Çeyrekler',
  'level.e3': 'Uzun yolculuk',

  's2.prizes': 'Seni bekleyen ödüller',
  's2.allCollected': 'Tüm ödüller toplandı! Artık görevler yıldız kazandırıyor.',
  's2.start': 'Başla',
  's2.back': 'Odaya dön',
  's2.locked': 'Seviyeler bir büyük tarafından kilitlendi',

  'a.story.space': 'Roketi hazırla!',
  'a.story.sweet': 'Çay partisini hazırla!',
  'a.read.q': 'Saat kaç?',
  'a.match.q': 'Hangi saat bunu gösteriyor: {time}?',
  'a.set.q': 'Saati {time} yap.',
  'a.set.check': 'Kontrol et',
  'a.set.wholeHours': "Tam saatlerde yelkovan 12'de kalır.",
  'a.set.minusHour': '− 1 saat',
  'a.set.plusHour': '+ 1 saat',
  'a.set.minusStep': '− {m} dk',
  'a.set.plusStep': '+ {m} dk',
  'a.match.label': 'Saat {letter}',
  'a.steps.space.1': 'Yakıt',
  'a.steps.space.2': 'Kapak',
  'a.steps.space.3': 'Işıklar',
  'a.steps.space.4': 'Geri sayım',
  'a.steps.sweet.1': 'Fincanlar',
  'a.steps.sweet.2': 'Pasta',
  'a.steps.sweet.3': 'Çaydanlık',
  'a.steps.sweet.4': 'Misafirler',

  'b.story.space': 'Paketin yolda!',
  'b.story.sweet': 'Oyun odasına bir paket geliyor!',
  'b.q.space': 'Yolculuk ne kadar sürer?',
  'b.q.sweet': 'Teslimat ne kadar sürer?',
  'b.leaves': 'Kalkış',
  'b.arrives': 'Varış',
  'b.showJumps': 'Adımları göster',
  'b.hideJumps': 'Adımları gizle',

  'dur.hm': '{h} saat {m} dakika',
  'dur.h1m': '1 saat {m} dakika',
  'dur.h': '{h} saat',
  'dur.h1': '1 saat',
  'dur.m': '{m} dakika',
  'dur.short.h': '+{h} sa',
  'dur.short.m': '+{m} dk',

  'period.morning': 'sabah',
  'period.afternoon': 'öğleden sonra',
  'period.evening': 'akşam',
  'period.night': 'gece',

  'q.progress': 'Soru {k} / 4',
  'q.hint': 'İpucu',
  'q.next': 'İleri',
  'q.leave': 'Çık',

  'hint.minutes': '{m} dakika',
  'hint.hourPast': 'Akrep {h} rakamını biraz geçmiş.',
  'hint.hourExact': 'Akrep tam {h} rakamını gösteriyor.',
  'hint.matchShort': 'akrep → {h}',
  'hint.matchLong': 'yelkovan → {m}',

  'fb.correct.1': 'Evet!',
  'fb.correct.2': 'İşte bu!',
  'fb.correct.3': 'Harika!',
  'fb.wrong.1': 'Henüz değil, tekrar dene.',
  'fb.wrong.2': 'Az kaldı. Tekrar bak.',
  'fb.wrong.3': 'Hmm, bir kez daha.',
  'fb.tryAgain': 'Tekrar dene',
  'fb.setWrong': 'Henüz değil. Akrebe bak.',

  'leave.title': 'Görevden çıkılsın mı?',
  'leave.body': 'Şimdiye kadarki bulmacalar kaybolur. Odan ve ödüllerin güvende.',
  'leave.confirm': 'Çık',
  'leave.cancel': 'Devam et',

  's5.title': 'Görev tamamlandı!',
  's5.sub': '4 saat bulmacası çözüldü',
  's5.choose': 'Ödülünü seç',
  's5.place': 'Odama koy',
  's5.wear': 'Giy',
  's5.keep': 'Oynamaya devam et',
  's5.star': 'Bir yıldız kazandın!',
  's5.starFull': 'Yıldız tablon doldu!',
  's5.backRoom': 'Odama dön',
  's5.preview': 'Oda önizlemesi',

  'prog.title': 'Daha büyük bir zorluğa hazır mısın?',
  'prog.try': '{level} dene',
  'prog.notYet': 'Henüz değil',

  's6.title': 'Ebeveyn köşesi',
  's6.hold': 'Basılı tut',
  's6.language': 'Dil',
  's6.levels': 'Seviyeler',
  's6.lock': 'Seviyeleri kilitle (çocuk değiştiremez)',
  's6.hour24': 'Okuma bulmacalarında 24 saatlik dijital saat',
  's6.sound': 'Ses',
  's6.motion': 'Hareket',
  's6.motion.system': 'Sistemi izle',
  's6.motion.reduced': 'Azaltılmış',
  's6.motion.full': 'Tam',
  's6.export': 'Kaydı dışa aktar',
  's6.import': 'Kayıt dosyası yükle',
  's6.reset': 'Her şeyi sıfırla (basılı tut)',
  's6.recent': 'Son görevler',
  's6.privacy': 'Hiçbir veri toplanmaz veya gönderilmez.',
  's6.done': 'Tamam',
  's6.damagedSave': 'Bozuk bir kayıt {date} tarihinde değiştirildi.',
  's6.newerSave': 'Daha yeni bir sürümden gelen kayıt {date} tarihinde kenara alındı.',

  'ui.soundOn': 'Ses açık',
  'ui.soundOff': 'Ses kapalı',
  'ui.parentCorner': 'Ebeveyn köşesi',
  'ui.language': 'Dil',

  'collection.space.moonSleepover': 'Ay Uykusu',
  'collection.space.rainbowExplorer': 'Gökkuşağı Kâşifi',
  'collection.sweet.sweetSleepover': 'Tatlı Uyku',
  'collection.sweet.sunnyGarden': 'Güneşli Bahçe',

  'item.shared.hairBuns': 'İki topuz',
  'item.shared.hairPonytail': 'Yüksek at kuyruğu',
  'item.shared.hairLoose': 'Tokalı açık saç',
  'item.shared.outfitPlanetTee': 'Gezegenli tişört ve nane etek',
  'item.shared.outfitFloralSweater': 'Çiçekli kazak ve salopet',
  'item.shared.outfitStarHoodie': 'Yıldızlı kapüşonlu ve pantolon',
  'item.shared.shoesSneakers': 'Sarı çorap ve spor ayakkabı',
  'item.shared.shoesMaryJanes': 'Pembe babet',

  'item.space.plainBed': 'Sade mavi yatak',
  'item.space.plainRug': 'Sade yuvarlak halı',
  'item.space.plainLamp': 'Sade lamba',
  'item.space.rocketPoster': 'Roket poster',
  'item.space.astronautFigure': 'Astronot figürü',
  'item.space.paperStars': 'Kağıt yıldız zinciri',
  'item.space.purpleBeanbag': 'Mor puf',
  'item.space.moonBed': 'Ay yatak',
  'item.space.starLamp': 'Yıldız lamba',
  'item.space.astroBunny': 'Astronot tavşan',
  'item.space.cloudPyjamas': 'Bulut pijama',
  'item.space.bunnySlippers': 'Tavşan terlik',
  'item.space.starClip': 'Yıldız toka',
  'item.space.rainbowRug': 'Gökkuşağı halı',
  'item.space.planetMobile': 'Gezegen mobil',
  'item.space.galaxyPoster': 'Galaksi poster',
  'item.space.spacesuit': 'Rengârenk uzay giysisi',
  'item.space.spaceBoots': 'Uzay botları',
  'item.space.rocketBackpack': 'Roket çanta',

  'item.sweet.plainBed': 'Sade pembe yatak',
  'item.sweet.plainRug': 'Sade puantiyeli halı',
  'item.sweet.plainLamp': 'Sade lamba',
  'item.sweet.tulipPicture': 'Lale resmi',
  'item.sweet.bunnyPlush': 'Peluş tavşan',
  'item.sweet.bunting': 'Bayrak süsü',
  'item.sweet.yellowCushion': 'Sarı koltuk minderi',
  'item.sweet.flowerCushion': 'Çiçek minder',
  'item.sweet.pastelRug': 'Pastel halı',
  'item.sweet.heartLamp': 'Kalp lamba',
  'item.sweet.floralPyjamas': 'Çiçekli pijama',
  'item.sweet.catSlippers': 'Kedi terlik',
  'item.sweet.flowerClip': 'Çiçek toka',
  'item.sweet.daisyBed': 'Papatya yatak',
  'item.sweet.butterflyMobile': 'Kelebek mobil',
  'item.sweet.sunPoster': 'Güneş poster',
  'item.sweet.strawberryDress': 'Çilek elbise',
  'item.sweet.rainbowSandals': 'Gökkuşağı sandalet',
  'item.sweet.bowHeadband': 'Fiyonk taç',
};
